name: laravel_raw

services:
  laravel:
    build: .
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    env_file:
      - ../../config.env
    container_name: laravel
