name: django_raw

services:
  django:
    build: .
    ports:
      - "80:8000"
    environment:
      - DJANGO_ENV=production
      - ALLOWED_HOSTS=*
    env_file:
      - ../../config.env
    container_name: django
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi
