name: astro_sql

services:
  database:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: postgres_db

  astro:
    build: .
    ports:
      - "80:4321"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4321
      - DATABASE_URL=postgresql://app_user:app_pass@database:5432/app_db
    depends_on:
      - database
    env_file:
      - ../../config.env
    container_name: astro_app

volumes:
  db-data: