name: astro_raw

services:
  astro:
    build: .
    ports:
      - "80:4321"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4321
    env_file:
      - ../../config.env
    container_name: astro_js