name: ruby_on_rails_json

services:
  ruby_on_rails:
    build: .
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - RAILS_MASTER_KEY=1eff506bfc7792135faa53e1dbc7cfdb
    env_file:
      - ../../config.env
    container_name: ruby_on_rails
